server:
  port: 5001 # 服务端口
spring:
  cloud:
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userServer # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
            - Before=2031-04-13T15:14:47.433+08:00[Asia/Shanghai]
        - id: order-service
          uri: lb://orderServer
          predicates:
            - Path=/order/**
      default-filters:
        - AddRequestHeader=Truth,cwh nb !