server:
  port: 6001 # 服务端口
spring:
  application:
    name: userServer-1
eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:7001/eureka
ribbon:
  eager-load:
    enabled: true
    clients: orderServer