server:
  port: 6001 # 服务端口
spring:
  application:
    name: userServer
  cloud:
    nacos:
      server-addr: http://127.0.0.1:8848
      discovery:
        cluster-name: GZ
#        namespace: fe759fbe-2521-4e46-b5de-d0d42ced734f
        ephemeral: true
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:7001/eureka
ribbon:
  eager-load:
    enabled: true
    clients: orderServer
orderServer:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
logging:
  level:
    com.cwh: debug
feign:
  client:
    config:
      orderServer:
        loggerLevel: BASIC
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
